include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI Utils for DNP3
APP_DEPENDS:=+dnp3 +vuci-app-universal-gateway-api

include ../api.mk

define Package/vuci-app-dnp3-utils-api/description
    DNP3 utils API.
endef

# call BuildPackage - OpenWrt buildroot signature
