include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI Common API Support for DNP3
APP_DEPENDS:=+dnp3 +vuci-app-universal-gateway-api

include ../api.mk

define Package/vuci-app-dnp3-common-api/description
    DNP3 common API.
endef

# call BuildPackage - OpenWrt buildroot signature
