include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for Modbus TCP over Serial Gateway

include ../app.mk

define Package/vuci-app-modbus-serial-gateway-ui/description
	Modbus RTU to TCP gateway designed to receive Modbus TCP message, convert to Modbus RTU and send it to Modbus RTU device.
endef

# call BuildPackage - OpenWrt buildroot signature
